-- =============================================================================
-- seed_lms_curriculum.sql -- Canonical WS7 curriculum as the catalogue (v0.43.0)
-- Upserts all 90 WS7 module shells by code (code/domain/level/owner/cadence/
-- mandatory/category), then archives the legacy code-less demo modules (the
-- Employee Handbook is preserved). DATA, not schema. Idempotent (upsert by code).
-- Bodies are NOT touched here (authored separately, e.g. seed_fnd103_content.sql).
-- All shells ship DRAFT except FND-103 (PUBLISHED, has content).
-- =============================================================================

BEGIN;

INSERT INTO "learning_modules"
  ("id","title","category","summary","status","code","domain","level","is_mandatory","cadence","owner","pass_mark","estimated_minutes","created_at","updated_at")
VALUES
  ($i$lm_fnd101$i$, $t$Welcome to Transworld: mission, values & the six behaviors$t$, 'Onboarding', $s$Who we are, what we value, and the six behaviors every Transworld person is held to.$s$, 'DRAFT', 'FND-101', 'FND', 'F', true, 'ON_JOIN', 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd102$i$, $t$How the firm works: structure, families, grades & the Growth Ladder$t$, 'Onboarding', $s$The firm's structure, job families, grades, and how careers grow along the Growth Ladder.$s$, 'DRAFT', 'FND-102', 'FND', 'F', true, 'ON_JOIN', 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd103$i$, $t$Code of Conduct & Ethics$t$, 'Compliance & Regulatory', $s$The binding standards of conduct every employee acknowledges — integrity, conflicts, and the line we will not cross.$s$, 'PUBLISHED', 'FND-103', 'FND', 'F', true, 'ON_JOIN_ANNUAL', 'CCO', 80, 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd104$i$, $t$AML/CFT & KYC Awareness$t$, 'Compliance & Regulatory', $s$Money-laundering and terrorist-financing risk, customer due diligence, red flags, and your reporting duty.$s$, 'DRAFT', 'FND-104', 'FND', 'F', true, 'ON_JOIN_ANNUAL', 'CCO', 80, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd105$i$, $t$Data Protection / NDPR$t$, 'Compliance & Regulatory', $s$Handling personal data lawfully under the NDPA/NDPR — the principles and your day-to-day obligations.$s$, 'DRAFT', 'FND-105', 'FND', 'F', true, 'ON_JOIN_ANNUAL', 'CCO', 80, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd106$i$, $t$Confidentiality & Information Security$t$, 'Compliance & Regulatory', $s$Protecting client and firm information — confidentiality duties and the information-security controls that bind you.$s$, 'DRAFT', 'FND-106', 'FND', 'F', true, 'ON_JOIN_ANNUAL', 'CCO', 80, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd107$i$, $t$Conflicts of Interest$t$, 'Compliance & Regulatory', $s$What a conflict is, the duty to disclose early in writing, and the activities that are restricted or prohibited.$s$, 'DRAFT', 'FND-107', 'FND', 'F', true, 'ON_JOIN_ANNUAL', 'CCO', 80, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd108$i$, $t$Whistleblowing & Speaking Up$t$, 'Compliance & Regulatory', $s$How to raise a concern, the routes available, your anonymity rights, and absolute protection against retaliation.$s$, 'DRAFT', 'FND-108', 'FND', 'F', true, 'ON_JOIN_ANNUAL', 'CCO', 80, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd109$i$, $t$SEC/NGX Conduct Essentials$t$, 'Compliance & Regulatory', $s$The regulatory framework we operate under and the market-conduct standards expected of a dealing member.$s$, 'DRAFT', 'FND-109', 'FND', 'F', true, 'ON_JOIN_ANNUAL', 'CCO', 80, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd110$i$, $t$Documentation discipline: what is not documented did not happen$t$, 'Compliance & Regulatory', $s$Why evidence and record-keeping are the backbone of a regulated firm, and how to document your work.$s$, 'DRAFT', 'FND-110', 'FND', 'F', true, 'ON_JOIN_ANNUAL', 'CCO', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd111$i$, $t$Owning your performance & development: navigating the Transworld P&D cycle$t$, 'Leadership & Professional', $s$How to own your goals, self-assessment, and growth across the firm's annual Performance & Development cycle — what to do at each stage, on joining and every year.$s$, 'DRAFT', 'FND-111', 'FND', 'F', true, 'ON_JOIN_ANNUAL', 'PEOPLE_OPS', 80, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd201$i$, $t$Working across teams & functions (the G2 collaboration shift)$t$, 'Leadership & Professional', $s$Moving from individual delivery to collaborating across teams as your responsibility grows.$s$, 'DRAFT', 'FND-201', 'FND', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fnd202$i$, $t$Professional communication & client-ready writing$t$, 'Leadership & Professional', $s$Writing clearly and professionally for colleagues, clients, and the record.$s$, 'DRAFT', 'FND-202', 'FND', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_cla101$i$, $t$Client onboarding & the KYC process$t$, 'Technical & Functional', $s$How a client becomes a client: onboarding steps, identity verification, and KYC completion.$s$, 'DRAFT', 'CLA-101', 'CLA', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_cla102$i$, $t$Who our clients are: customers vs. clients$t$, 'Technical & Functional', $s$Understanding the firm's client types and what each relationship means.$s$, 'DRAFT', 'CLA-102', 'CLA', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_cla201$i$, $t$Client relationship management & retention$t$, 'Technical & Functional', $s$Building durable client relationships, handling complaints well, and re-engaging dormant accounts.$s$, 'DRAFT', 'CLA-201', 'CLA', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_cla202$i$, $t$Enhanced Due Diligence & complex onboarding$t$, 'Technical & Functional', $s$When standard KYC isn't enough: EDD, higher-risk clients, and complex onboarding.$s$, 'DRAFT', 'CLA-202', 'CLA', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_cla203$i$, $t$Suitability & the basics of investment advisory$t$, 'Technical & Functional', $s$Matching advice to a client's needs, risk appetite, and circumstances — the suitability obligation.$s$, 'DRAFT', 'CLA-203', 'CLA', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_cla301$i$, $t$Advanced investment advisory & wealth engineering$t$, 'Technical & Functional', $s$Sophisticated advisory across goals, products, and portfolios for demanding clients.$s$, 'DRAFT', 'CLA-301', 'CLA', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_cla302$i$, $t$Managing high-net-worth & institutional relationships$t$, 'Technical & Functional', $s$Serving HNW and institutional clients and the expectations that come with them.$s$, 'DRAFT', 'CLA-302', 'CLA', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fin101$i$, $t$Financial accounting fundamentals$t$, 'Technical & Functional', $s$The language of accounting: the statements, the equation, and how transactions flow.$s$, 'DRAFT', 'FIN-101', 'FIN', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fin102$i$, $t$Bookkeeping, ledgers & reconciliation basics$t$, 'Technical & Functional', $s$Keeping the books: ledgers, journals, and the discipline of reconciliation.$s$, 'DRAFT', 'FIN-102', 'FIN', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fin201$i$, $t$Management & statutory reporting$t$, 'Technical & Functional', $s$Producing management accounts and the statutory and regulatory reports the firm must file.$s$, 'DRAFT', 'FIN-201', 'FIN', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fin202$i$, $t$Budgeting, forecasting & planning$t$, 'Technical & Functional', $s$Building and managing the firm's budget and financial forecasts.$s$, 'DRAFT', 'FIN-202', 'FIN', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fin203$i$, $t$Treasury & cash management$t$, 'Technical & Functional', $s$Managing the firm's cash, client deposits, and payment controls.$s$, 'DRAFT', 'FIN-203', 'FIN', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fin204$i$, $t$Tax & statutory compliance (PAYE, VAT, CIT)$t$, 'Technical & Functional', $s$The firm's tax obligations — PAYE, VAT, and company income tax — and staying compliant.$s$, 'DRAFT', 'FIN-204', 'FIN', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fin301$i$, $t$Financial strategy & capital adequacy (incl. SEC capital transition)$t$, 'Technical & Functional', $s$Capital planning, adequacy, and navigating the SEC minimum-capital transition.$s$, 'DRAFT', 'FIN-301', 'FIN', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_fin302$i$, $t$Controllership & audit management$t$, 'Technical & Functional', $s$The controller's role and managing internal and external audits.$s$, 'DRAFT', 'FIN-302', 'FIN', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_inv101$i$, $t$Capital markets & the NGX: how it all works$t$, 'Technical & Functional', $s$How Nigeria's capital market and the NGX operate, end to end.$s$, 'DRAFT', 'INV-101', 'INV', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_inv102$i$, $t$Market data & basic analysis$t$, 'Technical & Functional', $s$Reading market data and the foundations of analysis.$s$, 'DRAFT', 'INV-102', 'INV', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_inv201$i$, $t$Equity research & financial statement analysis$t$, 'Technical & Functional', $s$Researching a company and analyzing its financial statements.$s$, 'DRAFT', 'INV-201', 'INV', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_inv202$i$, $t$Valuation methods & building a research model$t$, 'Technical & Functional', $s$Core valuation techniques and constructing a research model.$s$, 'DRAFT', 'INV-202', 'INV', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_inv203$i$, $t$Writing the research note & making a recommendation$t$, 'Technical & Functional', $s$Turning analysis into a clear, defensible research note and recommendation.$s$, 'DRAFT', 'INV-203', 'INV', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_inv204$i$, $t$Portfolio construction & management basics$t$, 'Technical & Functional', $s$Building and managing a portfolio: diversification, allocation, and risk.$s$, 'DRAFT', 'INV-204', 'INV', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_inv301$i$, $t$Advanced valuation & sector deep-dives$t$, 'Technical & Functional', $s$Advanced valuation and sector-specific analysis.$s$, 'DRAFT', 'INV-301', 'INV', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_inv302$i$, $t$Portfolio strategy & discretionary management$t$, 'Technical & Functional', $s$Setting portfolio strategy and running discretionary mandates.$s$, 'DRAFT', 'INV-302', 'INV', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_inv303$i$, $t$Leading a research function & setting the agenda$t$, 'Technical & Functional', $s$Leading research: coverage, standards, and the house view.$s$, 'DRAFT', 'INV-303', 'INV', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ldr101$i$, $t$Ownership mentality: acting like an owner at any level$t$, 'Leadership & Professional', $s$Taking ownership and acting like an owner, whatever your grade.$s$, 'DRAFT', 'LDR-101', 'LDR', 'F', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ldr201$i$, $t$From doer to developer: the transition to leading a team$t$, 'Leadership & Professional', $s$The shift from doing the work to developing the people who do it.$s$, 'DRAFT', 'LDR-201', 'LDR', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ldr202$i$, $t$Delegation, coaching & developing others$t$, 'Leadership & Professional', $s$Delegating well and coaching your people to grow.$s$, 'DRAFT', 'LDR-202', 'LDR', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ldr203$i$, $t$Giving feedback & running the performance cycle$t$, 'Leadership & Professional', $s$Honest feedback and running the performance cycle fairly.$s$, 'DRAFT', 'LDR-203', 'LDR', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ldr204$i$, $t$Time, space & resources: enabling a team$t$, 'Leadership & Professional', $s$Clearing the path so your team can do its best work.$s$, 'DRAFT', 'LDR-204', 'LDR', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ldr301$i$, $t$Leading a function & leading other leaders$t$, 'Leadership & Professional', $s$Stepping up to lead a function and to lead other leaders.$s$, 'DRAFT', 'LDR-301', 'LDR', 'E', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ldr302$i$, $t$Strategic leadership & casting vision$t$, 'Leadership & Professional', $s$Setting direction and bringing people with you.$s$, 'DRAFT', 'LDR-302', 'LDR', 'E', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ldr303$i$, $t$Corporate governance & board-level stewardship$t$, 'Leadership & Professional', $s$Governance, board duties, and stewardship of the firm.$s$, 'DRAFT', 'LDR-303', 'LDR', 'E', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ops101$i$, $t$Operations fundamentals & the trade lifecycle$t$, 'Technical & Functional', $s$How operations works and the full trade lifecycle, front to back.$s$, 'DRAFT', 'OPS-101', 'OPS', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ops102$i$, $t$The seven-point mandate verification checklist$t$, 'Technical & Functional', $s$Verifying a client mandate before a trade — the firm's seven-point check.$s$, 'DRAFT', 'OPS-102', 'OPS', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ops201$i$, $t$Trade execution, settlement & the CSCS$t$, 'Technical & Functional', $s$Execution, settlement timelines, and how the CSCS fits in.$s$, 'DRAFT', 'OPS-201', 'OPS', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ops202$i$, $t$Process documentation & building checklists$t$, 'Technical & Functional', $s$Writing the procedures and checklists that make operations repeatable and auditable.$s$, 'DRAFT', 'OPS-202', 'OPS', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ops203$i$, $t$Internal controls & the control environment$t$, 'Technical & Functional', $s$What internal controls are and how the firm's control environment protects it.$s$, 'DRAFT', 'OPS-203', 'OPS', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ops301$i$, $t$Operations management & continuous improvement$t$, 'Technical & Functional', $s$Running operations and improving it continuously.$s$, 'DRAFT', 'OPS-301', 'OPS', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ops302$i$, $t$Internal audit & assurance$t$, 'Technical & Functional', $s$How internal audit and assurance test the firm's controls.$s$, 'DRAFT', 'OPS-302', 'OPS', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_reg101$i$, $t$The regulatory landscape: SEC, NGX & the rulebook$t$, 'Compliance & Regulatory', $s$The regulators, the rulebook, and how they shape what we do.$s$, 'DRAFT', 'REG-101', 'REG', 'F', false, NULL, 'CCO', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_reg201$i$, $t$AML/CFT program & transaction monitoring$t$, 'Compliance & Regulatory', $s$Running the AML/CFT program and monitoring transactions.$s$, 'DRAFT', 'REG-201', 'REG', 'P', false, NULL, 'CCO', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_reg202$i$, $t$Regulatory reporting & filings$t$, 'Compliance & Regulatory', $s$The firm's regulatory reports and filing calendar.$s$, 'DRAFT', 'REG-202', 'REG', 'P', false, NULL, 'CCO', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_reg203$i$, $t$Risk management fundamentals$t$, 'Compliance & Regulatory', $s$Identifying, assessing, and managing risk across the firm.$s$, 'DRAFT', 'REG-203', 'REG', 'P', false, NULL, 'CCO', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_reg204$i$, $t$Fit-and-proper & sponsored-individual obligations$t$, 'Compliance & Regulatory', $s$Fit-and-proper requirements and the duties of sponsored individuals.$s$, 'DRAFT', 'REG-204', 'REG', 'P', false, NULL, 'CCO', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_reg301$i$, $t$Building & running a compliance framework$t$, 'Compliance & Regulatory', $s$Designing and operating a full compliance framework.$s$, 'DRAFT', 'REG-301', 'REG', 'E', false, NULL, 'CCO', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_reg302$i$, $t$Managing examinations, enforcement & the CIA license$t$, 'Compliance & Regulatory', $s$Handling regulatory examinations, enforcement, and the firm's licence.$s$, 'DRAFT', 'REG-302', 'REG', 'E', false, NULL, 'CCO', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_reg303$i$, $t$Enterprise risk management$t$, 'Compliance & Regulatory', $s$Risk management at the enterprise level.$s$, 'DRAFT', 'REG-303', 'REG', 'E', false, NULL, 'CCO', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_tec101$i$, $t$Using the PeopleOps portal & the firm's systems$t$, 'Technical & Functional', $s$Getting productive in the PeopleOps portal and the firm's core systems.$s$, 'DRAFT', 'TEC-101', 'TEC', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_tec102$i$, $t$Cyber hygiene & safe data handling$t$, 'Technical & Functional', $s$Everyday cyber hygiene and handling data safely.$s$, 'DRAFT', 'TEC-102', 'TEC', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_tec201$i$, $t$The Naya system & trading platforms$t$, 'Technical & Functional', $s$Working with the Naya system and the firm's trading platforms.$s$, 'DRAFT', 'TEC-201', 'TEC', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_tec202$i$, $t$Data protection (NDPR) in practice$t$, 'Technical & Functional', $s$Applying NDPR data-protection rules in day-to-day work.$s$, 'DRAFT', 'TEC-202', 'TEC', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_tec301$i$, $t$IT systems administration & security$t$, 'Technical & Functional', $s$Administering and securing the firm's IT systems.$s$, 'DRAFT', 'TEC-301', 'TEC', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_tec302$i$, $t$IT governance, backup & business continuity$t$, 'Technical & Functional', $s$IT governance, backups, and keeping the firm running through disruption.$s$, 'DRAFT', 'TEC-302', 'TEC', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv101$i$, $t$Business development at Transworld: the role, the mandate & representing the institution$t$, 'Technical & Functional', $s$What the BD role is, the mandate you carry, and what it means to represent Transworld in the market.$s$, 'DRAFT', 'BDV-101', 'BDV', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv102$i$, $t$Know what you sell: the firm's products, services & financial instruments$t$, 'Technical & Functional', $s$The products, services, and instruments the firm offers — and what each one actually is.$s$, 'DRAFT', 'BDV-102', 'BDV', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv103$i$, $t$Talking markets in plain language: explaining securities to the layperson$t$, 'Technical & Functional', $s$Explaining markets and securities clearly to clients who aren't specialists.$s$, 'DRAFT', 'BDV-103', 'BDV', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv104$i$, $t$Prospecting & lead generation: finding and reaching new customers$t$, 'Technical & Functional', $s$Finding, qualifying, and reaching prospective clients.$s$, 'DRAFT', 'BDV-104', 'BDV', 'F', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv201$i$, $t$Consultative selling: discovery, needs analysis & building trust$t$, 'Technical & Functional', $s$Selling by understanding needs first: discovery, analysis, and earning trust.$s$, 'DRAFT', 'BDV-201', 'BDV', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv202$i$, $t$The sales funnel: pipeline, CRM discipline & managing your numbers$t$, 'Technical & Functional', $s$Running a disciplined pipeline and managing your numbers through the funnel.$s$, 'DRAFT', 'BDV-202', 'BDV', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv203$i$, $t$Proposals & pitching: winning the business & post-proposal follow-through$t$, 'Technical & Functional', $s$Building proposals, pitching well, and following through to win the business.$s$, 'DRAFT', 'BDV-203', 'BDV', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv204$i$, $t$Handling objections, negotiation & ethical closing$t$, 'Technical & Functional', $s$Working through objections, negotiating fairly, and closing the right way.$s$, 'DRAFT', 'BDV-204', 'BDV', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv205$i$, $t$Compliant selling: market conduct, suitability, inducements & what you may say$t$, 'Technical & Functional', $s$The conduct rules around selling: suitability, inducements, and what you may and may not say.$s$, 'DRAFT', 'BDV-205', 'BDV', 'P', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv301$i$, $t$Leading a BD team: targets, coaching the funnel & sales management$t$, 'Technical & Functional', $s$Leading a BD team: setting targets, coaching the funnel, and managing performance.$s$, 'DRAFT', 'BDV-301', 'BDV', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv302$i$, $t$Strategic origination: HNW, corporate & institutional business development$t$, 'Technical & Functional', $s$Originating high-net-worth, corporate, and institutional business.$s$, 'DRAFT', 'BDV-302', 'BDV', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_bdv303$i$, $t$Building the BD engine: go-to-market, partnerships, brand & referral ecosystems$t$, 'Technical & Functional', $s$Building the firm's growth engine: go-to-market, partnerships, brand, and referrals.$s$, 'DRAFT', 'BDV-303', 'BDV', 'E', false, NULL, 'FUNCTION_HEAD', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl101$i$, $t$The People Operations function: charter, mandate & the employee lifecycle$t$, 'Technical & Functional', $s$What People Operations is for: its charter, mandate, and the full employee lifecycle.$s$, 'DRAFT', 'PPL-101', 'PPL', 'F', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl102$i$, $t$People data, confidentiality & NDPR for HR$t$, 'Technical & Functional', $s$Handling employee data lawfully and confidentially under the NDPA/NDPR.$s$, 'DRAFT', 'PPL-102', 'PPL', 'F', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl201$i$, $t$Workforce architecture: grades, job families, competencies & role scorecards$t$, 'Technical & Functional', $s$The firm's grades, job families, competencies, and how role scorecards are built.$s$, 'DRAFT', 'PPL-201', 'PPL', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl202$i$, $t$Recruitment & hiring: the ten-stage workflow, structured interviewing & fit-and-proper$t$, 'Technical & Functional', $s$The ten-stage hiring workflow, structured interviewing, and fit-and-proper checks.$s$, 'DRAFT', 'PPL-202', 'PPL', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl203$i$, $t$Onboarding, probation & exit administration$t$, 'Technical & Functional', $s$Administering onboarding, probation, and exits cleanly and on the record.$s$, 'DRAFT', 'PPL-203', 'PPL', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl204$i$, $t$Performance management & the competency-scorecard cycle$t$, 'Technical & Functional', $s$Running the performance cycle and the competency scorecard, end to end.$s$, 'DRAFT', 'PPL-204', 'PPL', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl205$i$, $t$Compensation, benefits & payroll operations$t$, 'Technical & Functional', $s$How pay, benefits, and the payroll cycle are operated and controlled.$s$, 'DRAFT', 'PPL-205', 'PPL', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl206$i$, $t$L&D administration & mandatory-training compliance$t$, 'Technical & Functional', $s$Administering learning and keeping mandatory-training compliance on track.$s$, 'DRAFT', 'PPL-206', 'PPL', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl207$i$, $t$Employee relations: discipline, grievance, anti-harassment & the speak-up interface$t$, 'Technical & Functional', $s$Discipline, grievance, anti-harassment, and the interface with speak-up channels.$s$, 'DRAFT', 'PPL-207', 'PPL', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl208$i$, $t$The People-Ops operating rhythm: running the weekly, monthly, quarterly & annual cadence$t$, 'Technical & Functional', $s$Running the People-Ops cadence across the week, month, quarter, and year.$s$, 'DRAFT', 'PPL-208', 'PPL', 'P', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl301$i$, $t$Leading People Operations: workforce planning, HR strategy & culture stewardship$t$, 'Technical & Functional', $s$Leading People Operations: workforce planning, strategy, and stewarding culture.$s$, 'DRAFT', 'PPL-301', 'PPL', 'E', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ($i$lm_ppl302$i$, $t$HR governance, controls & audit readiness$t$, 'Technical & Functional', $s$HR governance, the controls that bind People-Ops, and staying audit-ready.$s$, 'DRAFT', 'PPL-302', 'PPL', 'E', false, NULL, 'PEOPLE_OPS', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (code) WHERE code IS NOT NULL DO UPDATE SET
  title = EXCLUDED.title, category = EXCLUDED.category, summary = EXCLUDED.summary,
  status = EXCLUDED.status, domain = EXCLUDED.domain, level = EXCLUDED.level,
  is_mandatory = EXCLUDED.is_mandatory, cadence = EXCLUDED.cadence, owner = EXCLUDED.owner,
  pass_mark = EXCLUDED.pass_mark, estimated_minutes = EXCLUDED.estimated_minutes,
  updated_at = CURRENT_TIMESTAMP;

-- archive the legacy code-less demo modules (preserve the Employee Handbook)
UPDATE "learning_modules" SET status = 'ARCHIVED', updated_at = CURRENT_TIMESTAMP
WHERE code IS NULL AND COALESCE(category,'') <> 'HANDBOOK' AND title NOT ILIKE '%handbook%';

COMMIT;