-- 0001_add_documents.sql
-- Transworld PeopleOps — reusable file/document registry backing Supabase Storage.
--
-- HOW TO APPLY: Supabase dashboard → SQL Editor → New query → paste this whole
-- file → Run. Additive only (creates one new table + one index); it does not
-- touch any existing table or data, and is safe to run once.
--
-- This table is the backbone for every file-using feature: job-description docs
-- (v0.8.0), role scorecards, the Evidence Vault, and employee staff files. A row
-- records WHERE a file lives in Storage (bucket + path) and WHAT it belongs to
-- (entity_type + entity_id), never the bytes themselves.
--
-- Note: `id` has no DB default on purpose — ids are generated by the application
-- layer (Prisma @default(cuid())), matching every other table in this schema.

create table if not exists public.documents (
  id              text        primary key,
  bucket          text        not null,
  path            text        not null unique,
  filename        text        not null,
  content_type    text,
  size_bytes      integer,
  category        text,
  entity_type     text        not null,
  entity_id       text        not null,
  uploaded_by_id  text,
  created_at      timestamptz not null default now()
);

create index if not exists documents_entity_idx
  on public.documents (entity_type, entity_id);
